#!/usr/bin/ruby

def print_env(pid)
  File.read("/proc/#{pid}/environ").split("\x00").sort.each do |envvar|
    puts envvar
  end
end


ARGV.each do |match_string|
  case match_string
  when /^[0-9]+$/
    print_env(match_string)
  else
    pid = `ps aux | grep -v grep | grep -i -e #{match_string} | head -n 1 | tail -n 1 | awk '{ print $2 }'`
    print_env(pid.strip)
  end
end
