#! /usr/bin/env bash

oneline="$(xclip -selection clipboard -o | sed ':a;N;$!ba;s/\n/ /g')"
if [ ${#oneline} -gt 100 ]; then
  truncated="$(echo "$oneline" | cut -c 1-100)"
  echo "$truncated..."
elif [ ${#oneline} -gt 0 ]; then
  echo "$oneline"
else
  echo "(empty)"
fi
