#! /usr/bin/env bash

LS_COLORS=$(ls_colors_generator)

run_ls() {
	ls-i -h --group-directories-first -1 --color=auto -w $(tput cols) "$@"
}

run_dir() {
	dir-i --color=auto -w $(tput cols) "$@"
}

run_vdir() {
	vdir-i --color=auto -w $(tput cols) "$@"
}
alias ls="run_ls"
alias dir="run_dir"
alias vdir="run_vdir"
