# https://starship.rs/config

add_newline = false

format = """
$username\
$hostname\
$shlvl\
$directory\
$package\
$env_var\
$custom\
$git_branch\
$git_commit\
$git_state\
$git_status\
$jobs\
$cmd_duration\
$character"""

[shlvl]
disabled = false
symbol = ""
format = "[fish#$shlvl]($style) "
style = "purple"

[directory]
style = "blue"

[git_branch]
symbol = ""

[git_commit]
format = "[$hash]($style) "

[git_state]
format = "[$state( $progress_current/$progress_total)]($style) "

[git_status]
conflicted = "\\[U$count\\]"
untracked ="\\[A$count\\]"

[package]
symbol = ""

[cmd_duration]
min_time = 30_000
