#!/usr/bin/env bash

message="$(cat "$1")"
if [[
      -n "$message" &&
      ! "$message" =~ ^# &&
      ! "$message" =~ ^\[[0-9]+|[A-Z]+-[0-9]+\][[:space:]] &&
      ! "$message" =~ ^[0-9]+([[:space:]]+#|$) &&
      ! "$message" =~ ^Merge[[:space:]] &&
      ! "$message" =~ ^fixup![[:space:]]
    ]]; then
  branch="$(git rev-parse --abbrev-ref HEAD)"
  if [[ "$branch" =~ ^([0-9]+|[A-Z]+-[0-9]+) ]]; then
    prefix="[${BASH_REMATCH[1]}]"
    prefixed="$prefix $message"
    echo "$prefixed" > "$1"
  fi
fi
