#!/usr/bin/env bash

upper() {
  printf '%s\n' "${1^^}"
}

branch() {
  fast_branch="$(git rev-parse --abbrev-ref HEAD)"
  if [[ "$fast_branch" = "HEAD" ]]; then
    git branch | grep -e "^*" | sed -E "s/\* //g;s/\(no branch, rebasing (.+)\)/\1/g"
  else
    echo "$fast_branch"
  fi
}

message="$(cat "$1")"
if [[
      -n "$message" &&
      ! "$message" =~ ^# &&
      ! "$message" =~ ^\[([0-9]+|[A-Z]+-[0-9]+)\][[:space:]] &&
      ! "$message" =~ ^[0-9a-z]+([[:space:]]+#|$) &&
      ! "$message" =~ ^Merge[[:space:]] &&
      ! "$message" =~ ^fixup![[:space:]]
    ]]; then
  if [[ "$(branch)" =~ ^([0-9]+|[A-Za-z]+-[0-9]+) ]]; then
    prefix="$(upper [${BASH_REMATCH[1]}])"
    prefixed="$prefix $message"
    echo "$prefixed" > "$1"
  fi
fi
